### ISSUE TITLE
getting error in Map module

### ISSUE THREAD

**Issue by shanmugavadivelps** [gFedonin/VirGenA#8]
I have run the tool as follows with ram of 35 gb 

java -jar VirGenA.jar map -c config_copy.xml 

got error 
DEBUG	2021-11-12 13:14:59	BlockCompressedOutputStream	Using deflater: Deflater
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at htsjdk.samtools.BAMFileWriter.writeAlignment(BAMFileWriter.java:127)
	at htsjdk.samtools.SAMFileWriterImpl.addAlignment(SAMFileWriterImpl.java:190)
	at BamPrinter.printBAM(BamPrinter.java:321)
	at Mapper.run(Mapper.java:574)
	at VirGenA.main(VirGenA.java:31)

**Comment by gFedonin** [comment]
Hello! Sorry for the late answer: I've missed the question somehow. Have you tried adding -Xmx30G option to java? By default it use only 4Gb. The full command will look like:

java -Xmx30G -jar VirGenA.jar map -c config_copy.xml

If this doesn't help, please tell me more details: the genome length, the read length, the number of reads.
